# AUTOGENERATED! DO NOT EDIT! File to edit: ../mmdet_model.ipynb.

# %% auto 0
__all__ = ['model', 'in_image', 'out_image', 'examples', 'intf']

# %% ../mmdet_model.ipynb 1
import torch, torchvision
import mmdet
from fastbook import *
from fastai.vision.widgets import *
from mmdet.core.visualization.image import my_output_for_gr
from mmdet.apis import inference_detector
import gradio as gr
model = pickle.load(open('simpcon_class_model.pkl', 'rb')).eval()

from mmdet.core.visualization.image import my_output_for_gr

def app_result(img):
    result = inference_detector(model, img)
    model.show_result(img, result, score_thr=0.45, text_color=(200, 200, 200))
    out = my_output_for_gr()
    return out


# %% ../mmdet_model.ipynb 4
in_image =  gr.components.Image()
examples = ['000000000016.jpg', 'test2.jpg', 'yoga1.jpg', 'yoga2.jpg', 'yoga3.jpg']
intf = gr.Interface(fn = app_result, inputs = in_image, outputs = in_image, examples = examples)
intf.launch(inline = True)


